services:
  - type: web
    name: digital-attendance-web
    env: python
    repo: https://github.com/Motongorii/Digital-Attendace-Systemm
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn attendance_system.wsgi --log-file -
databases:
  - name: attendance-db
    plan: free
